server:
  port: 8081
spring:
  application:
    name: vdt
  datasource:
    url: jdbc:mariadb://localhost:3307/demo_db?createDatabaseIfNotExist=true
    username: root
    password: 555555
    driver-class-name: org.mariadb.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/demo-realm
          jwk-set-uri: http://localhost:8080/realms/demo-realm/protocol/openid-connect/certs
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false